# Generated by Django 4.2.16 on 2024-10-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('view_movies', models.CharField(choices=[('fi', 'Фильм'), ('se', 'Сериал'), ('cs', 'Мультсериал'), ('ca', 'Мультфильм')], max_length=2, verbose_name='Вид контента')),
                ('category', models.CharField(choices=[('Thr', 'Триллер'), ('Wes', 'Вестерн'), ('Act', 'Экшн'), ('His', 'Исторический'), ('Fan', 'Фэнтези '), ('Adv', 'Приключение'), ('Spo', 'Спорт'), ('Dra', 'Драма'), ('Com', 'Комедия'), ('Hor', 'Ужасы')], max_length=4, verbose_name='Категория')),
            ],
        ),
    ]
