# Generated by Django 4.2.16 on 2024-10-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_movie_rank_alter_movie_view_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rank',
        ),
        migrations.AlterField(
            model_name='movie',
            name='view_movies',
            field=models.CharField(choices=[('se', 'Сериал'), ('fi', 'Фильм'), ('cs', 'Мультсериал'), ('ca', 'Мультфильм')], max_length=2, verbose_name='Вид контента'),
        ),
    ]
